kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data
  namespace: sdn-mars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #volumeName: pvc-b50945bf-7160-4bf3-9c45-751f505d3c32
  #storageClassName: ""
  volumeMode: Filesystem
