apiVersion: v1
kind: Namespace
metadata:
  name: sdn-mars
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data
  namespace: sdn-mars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #storageClassName: ""
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mars-download
  namespace: sdn-mars
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #storageClassName: ""
  volumeMode: Filesystem
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mars
  namespace: sdn-mars
  labels:
    app: mars
  annotations:
    deployment.kubernetes.io/revision: '25'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mars
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mars
      annotations:
        kubesphere.io/creator: admin
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-8phuxc
          persistentVolumeClaim:
            claimName: es-data
        - name: volume-qqp3ko
          persistentVolumeClaim:
            claimName: mars-download
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
            - sh
            - '-c'
            - >-
              sysctl -w vm.max_map_count=262144 && chmod a+w
              /usr/share/elasticsearch/data
        volumeMounts:
            - name: volume-8phuxc
              mountPath: /usr/share/elasticsearch/data
              subPath: data
        securityContext:
          privileged: true
      containers:
        - name: container-mars
          image: 'nocsysmars/mars:master'
          ports:
            - name: http-0
              containerPort: 8101
              protocol: TCP
            - name: http-1
              containerPort: 8181
              protocol: TCP
          env:
            - name: ONOS_TOPOLOGY
              value: clos
            - name: ONOS_APPS
              value: >-
                drivers,com.accton.drivers.accton.gnmi,com.accton.drivers.accton.rest,com.accton.drivers.accton.snmp,proxyarp,restsb,snmp,org.onosproject.netconf,org.onosproject.drivers.netconf,org.onosproject.drivers.h3c.netconf,linkdiscovery,com.accton.provider.switchpolling,com.accton.eventclient,com.accton.useraccount,com.accton.defaultcfg,com.accton.alert,com.accton.analyzer,com.accton.utility,com.accton.healthycheck,com.accton.logicalport,com.accton.endpoint,com.accton.monitor,com.accton.ntpserver,com.accton.qos,com.accton.sflow,com.accton.storm-control,com.accton.switchmgmt,com.accton.acl,com.accton.websocket,com.accton.webssh
            - name: ONOS_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ES_HOSTS
              value: '127.0.0.1:9200'
          resources:
            limits:
              memory: 1000Mi
            requests:
              cpu: 500m
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-qqp3ko
              mountPath: /root/onos/download
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: container-nginx
          image: 'nocsysmars/nginx:1.14.0-mars'
          ports:
            - name: tcp-443
              containerPort: 443
              protocol: TCP
            - name: tcp-69
              containerPort: 69
              protocol: TCP
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 1000Mi
            requests:
              cpu: 10m
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: container-logstash
          image: 'nocsysmars/logstash:7.5.2-oss'
          ports:
            - name: tcp-25826
              containerPort: 25826
              protocol: TCP
            - name: tcp-5044
              containerPort: 5044
              protocol: TCP
            - name: tcp-514
              containerPort: 514
              protocol: TCP
            - name: tcp-5514
              containerPort: 5514
              protocol: TCP
            - name: tcp-6343
              containerPort: 6343
              protocol: TCP
            - name: tcp-6614
              containerPort: 6614
              protocol: TCP
            - name: tcp-9600
              containerPort: 9600
              protocol: TCP
          env:
            - name: ES_HOSTS
              value: 127.0.0.1
          resources:
            limits:
              memory: 1000Mi
            requests:
              cpu: 500m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: container-es
          image: 'nocsysmars/elasticsearch:7.9.0-oss'
          ports:
            - name: tcp-9200
              containerPort: 9200
              protocol: TCP
            - name: tcp-9300
              containerPort: 9300
              protocol: TCP
          env:
            - name: cluster.name
              value: marsesdb
            - name: ES_JAVA_OPTS
              value: ' -Xms256m -Xmx256m'
            - name: node.master
              value: 'true'
            - name: discovery.zen.minimum_master_nodes
              value: '1'
            - name: cluster.initial_master_nodes
              value: marsdb-node
            - name: node.name
              value: marsdb-node
            - name: network.host
              value: 127.0.0.1
            - name: network.publish_host
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            limits:
              memory: 1000Mi
            requests:
              cpu: 500m
          volumeMounts:
            - name: volume-8phuxc
              mountPath: /usr/share/elasticsearch/data
              subPath: data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: mars
  namespace: sdn-mars
  labels:
    app: mars
  annotations:
    kubesphere.io/creator: admin
spec:
  ports:
    - name: web
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30913
    - name: download
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31499
  selector:
    app: mars
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
