apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sdn-mars
  name: mars-download
  labels: {}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 #storageClassName: cstor-csi-disk
